#!/usr/bin/perl -w -Ilib/
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

BEGIN{ use_ok( 'Carp' ); }
require_ok( 'Carp' );


BEGIN{ use_ok( 'ConfigFile' ); }
require_ok( 'ConfigFile' );


BEGIN{ use_ok( 'Digest::MD5' ); }
require_ok( 'Digest::MD5' );


BEGIN{ use_ok( 'Encode' ); }
require_ok( 'Encode' );


BEGIN{ use_ok( 'Encode::Guess' ); }
require_ok( 'Encode::Guess' );


BEGIN{ use_ok( 'English' ); }
require_ok( 'English' );


BEGIN{ use_ok( 'Env' ); }
require_ok( 'Env' );


BEGIN{ use_ok( 'Exporter' ); }
require_ok( 'Exporter' );


BEGIN{ use_ok( 'File::Find' ); }
require_ok( 'File::Find' );


BEGIN{ use_ok( 'File::Spec' ); }
require_ok( 'File::Spec' );


BEGIN{ use_ok( 'Getopt::Long' ); }
require_ok( 'Getopt::Long' );


BEGIN{ use_ok( 'gnump3d::base64' ); }
require_ok( 'gnump3d::base64' );


BEGIN{ use_ok( 'gnump3d::config' ); }
require_ok( 'gnump3d::config' );


BEGIN{ use_ok( 'gnump3d::files' ); }
require_ok( 'gnump3d::files' );


BEGIN{ use_ok( 'gnump3d::filetypes' ); }
require_ok( 'gnump3d::filetypes' );


BEGIN{ use_ok( 'gnump3d::IP' ); }
require_ok( 'gnump3d::IP' );


BEGIN{ use_ok( 'gnump3d::lang::lookup' ); }
require_ok( 'gnump3d::lang::lookup' );


BEGIN{ use_ok( 'gnump3d::MD5' ); }
require_ok( 'gnump3d::MD5' );


BEGIN{ use_ok( 'gnump3d::mp3info' ); }
require_ok( 'gnump3d::mp3info' );


BEGIN{ use_ok( 'gnump3d::mp4info' ); }
require_ok( 'gnump3d::mp4info' );


BEGIN{ use_ok( 'gnump3d::ogginfo' ); }
require_ok( 'gnump3d::ogginfo' );


BEGIN{ use_ok( 'gnump3d::readtags' ); }
require_ok( 'gnump3d::readtags' );


BEGIN{ use_ok( 'gnump3d::Request' ); }
require_ok( 'gnump3d::Request' );


BEGIN{ use_ok( 'gnump3d::sorting' ); }
require_ok( 'gnump3d::sorting' );


BEGIN{ use_ok( 'gnump3d::tagcache' ); }
require_ok( 'gnump3d::tagcache' );


BEGIN{ use_ok( 'gnump3d::url' ); }
require_ok( 'gnump3d::url' );


BEGIN{ use_ok( 'gnump3d::WMA' ); }
require_ok( 'gnump3d::WMA' );


BEGIN{ use_ok( 'integer' ); }
require_ok( 'integer' );


BEGIN{ use_ok( 'IO::File' ); }
require_ok( 'IO::File' );


BEGIN{ use_ok( 'IO::Socket' ); }
require_ok( 'IO::Socket' );


BEGIN{ use_ok( 'overload' ); }
require_ok( 'overload' );


BEGIN{ use_ok( 'Pod::Usage' ); }
require_ok( 'Pod::Usage' );


BEGIN{ use_ok( 'POSIX' ); }
require_ok( 'POSIX' );


BEGIN{ use_ok( 'sigtrap' ); }
require_ok( 'sigtrap' );


BEGIN{ use_ok( 'Socket' ); }
require_ok( 'Socket' );


BEGIN{ use_ok( 'strict' ); }
require_ok( 'strict' );


BEGIN{ use_ok( 'Symbol' ); }
require_ok( 'Symbol' );


BEGIN{ use_ok( 'Test::More' ); }
require_ok( 'Test::More' );


BEGIN{ use_ok( 'vars' ); }
require_ok( 'vars' );


BEGIN{ use_ok( 'warnings' ); }
require_ok( 'warnings' );


